apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phonebook-result-server
  template:
    metadata:
      labels:
        app: phonebook-result-server
    spec:
      containers:
        - name:  phonebook-result-server
          image: muratyarali/phonebook_resultserver:1.0
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user-password
          envFrom:
            - configMapRef:
                name: servers-configmap
