apiVersion: v1
kind: Service
metadata:
  name: web-flask-svc
  namespace: demo
  labels:
    app: web-flask
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 5000
  selector:
    app: web-flask
    version: v1